[12.0] Do not require AWS_BUCKETNAME if ODOO_DEV_KEEP_ATTACHMENT_S3 is set
camptocamp/odoo-cloud-platform pull request #141
Opened 2020-02-05 08:51 UTC by grindtildeath

AWS_BUCKETNAME is only needed in order to write on the bucket, but
read-only access should be allowed for DEV.

2020-02-17 08:38 UTC, simahawk commented on cloud_platform/models/cloud_platform.py
> +                os.environ.get('ODOO_DEV_KEEP_ATTACHMENT_S3')
what about `AWS_BUCKET_READONLY`?
Also, shall we document it somewhere?

2020-02-17 09:47 UTC, Tonow-c2c approved these changes
LGTM with answer about @simahawk question

2020-02-19 07:49 UTC, jcoux requested changes

2020-02-19 07:49 UTC, jcoux commented on cloud_platform/models/cloud_platform.py
> +                os.environ.get('ODOO_DEV_KEEP_ATTACHMENT_S3')
To be consistent, we need to use a common variable for S3 and SWIFT.
The modification here must be added also into function `_check_swift` just above this function.
And the name of environment variable must be changed into odoo-template: https://github.com/camptocamp/odoo-template/blob/stable/%7B%7Bcookiecutter.repo_name%7D%7D/odoo/before-migrate-entrypoint.d/000_dev_set_db_storage#L9

2020-02-24 10:26 UTC, grindtildeath commented
@simahawk Kind of agree with @jcoux , would make sense to use only one var name for both s3 and swift.

So what do we want to use ? 
1. ODOO_DEV_KEEP_ATTACHMENT_S3 (easiest change since it's the same var used on odoo-template and the provided solution works. We'd still need to add the same `or` condition for swift but the name is then misleading.)
2. ODOO_DEV_KEEP_ATTACHMENT (it only states we keep attachments whatever the storage that is used use and the provided solution works. We'd still need to add the same `or` condition for swift and do the change on odoo-template + all the projects)
3. STORAGE_READONLY (if we want to set such a var, we must ensure _store_file_write and _store_file_delete are overriden to make sure we're in a readonly mode, Might make the setting less obvious since we must handle the case where both the bucketname and this var are set to make sure it won't have side effects. Moreover we'd still need to add the same `or` condition for swift and do the change on odoo-template + all the projects)

Personally I'd favor option 2...

2020-02-24 10:38 UTC, guewen requested changes
It looks like a leak of our project's template into this module. I don't think we should have such variable at all. 
Actually, it's a mistake I introduced lately in: https://github.com/camptocamp/odoo-cloud-platform/commit/6c3b610610d7a1c1bc5e51c57840bc67d976dcb3

We used to be able to start odoo using aws accesses but no bucket name before my PR.

The correct solution IMO is to make this check only on a selection of environments (prod, integration, labs) and not introduce a custom variable.

2020-02-24 10:54 UTC, grindtildeath commented
@guewen I reworked the PR according to your last comment. Still, as I understand, we don't want to run this check on `labs` ?

2020-02-25 14:54 UTC, guewen approved these changes

2020-02-25 14:55 UTC, guewen commented
> Still, as I understand, we don't want to run this check on `labs` ?

Discussed this directly but for the record, we want to check this. (using a different `ir_attachment.location` for labs is allowed, but if the value is `s3` or `swift`, the lab will run into issues if the bucket name is not set.

2020-02-25 15:35 UTC, yvaucher commented
This is conflicting due to #116 that I just merged. (it was open since a while)

Tell me if you need help to resolve the conflict.

2020-02-26 06:53 UTC, jcoux approved these changes
Thanks for changes.

2020-02-26 13:40 UTC, merged