WIP: [IMP] attachment_s3
camptocamp/odoo-cloud-platform pull request #216
Opened 2021-01-28 03:55 UTC by max3903

2021-01-30 23:13 UTC, max3903 commented
@guewen This is ready to be reviewed.

2021-03-01 02:16 UTC, gustavovalverde approved these changes

2021-04-07 18:01 UTC, yvaucher requested changes
It breaks the check on line 66

I guess there is no magic there, changing the bucket name computation force the users to rename their buckets?

2021-04-07 18:01 UTC, yvaucher commented on attachment_s3/models/ir_attachment.py
> +        bucket_name = name or os.environ.get("AWS_BUCKETNAME") + "-" + self.env.cr.dbname
Same concerns as on #218 

Isn't this a breaking change for existing instance with single database?

Plus, this give always a value to `bucket_name`

Which breaks the condition test on line 66

2021-05-27 16:21 UTC, yvaucher commented
Superseeded by https://github.com/camptocamp/odoo-cloud-platform/pull/227

2021-05-27 16:21 UTC, closed without merging