[ADD] attachment_azure
camptocamp/odoo-cloud-platform pull request #225
Opened 2021-05-20 14:54 UTC by max3903

Closes #222 

Still missing #223 

CC @hiren-serpentcs

2021-05-27 09:05 UTC, yvaucher commented
Nice! I'll check that next week.

2021-05-27 09:10 UTC, p-tombez commented
Looks promising. Would you consider adding the same mechanic for the storage name as in #224 ?

2021-05-27 15:50 UTC, max3903 commented
@p-tombez It is already taken care of here: https://github.com/camptocamp/odoo-cloud-platform/pull/225/files#diff-2f8200ae96993037ee309fce2e5b6eaae1bcfabc8613bc549dfe2b46c29c6285R96

2021-05-28 07:28 UTC, p-tombez commented
@max3903 I don't think it's the same. Here, we don't have any control on the name instead of having an environment variable like in #224 where you can actually choose a name and add a placeholder in it for the DB name

2021-05-28 13:09 UTC, max3903 commented
@p-tombez Azure does not have the concept of a bucket. You create a storage account and a shared access signature and you get:
- a connection string
- a signature
- a sas url

With those credentials, we create a container for each database. So the storage account is multi tenant.

Additional argument for this, when Odoo uses the filesystem, you don't have the control on the name of the directory.

2021-05-28 14:09 UTC, max3903 commented
@p-tombez 

```
$ cat ~/.config/rclone/rclone.conf
[remote]
type = azureblob
sas_url = https://<storageaccountname>.blob.core.*****.net/?*********
$ rclone lsd remote:
          -1 2021-05-26 21:58:42        -1 backup
          -1 2021-05-22 17:20:16        -1 production-master
          -1 2021-05-27 02:13:57        -1 qa-backup
          -1 2021-05-22 01:52:30        -1 qa-test
          -1 2021-05-27 21:35:13        -1 test-20210527
          -1 2021-05-27 21:09:46        -1 test-backup
```

2021-05-31 07:39 UTC, yvaucher requested changes
Thanks for the module

Here are few remarks on Exception handling and for the parameters.

2021-05-31 07:39 UTC, yvaucher commented on attachment_azure/models/ir_attachment.py
> +        if not (connect_str or account_name or account_url or account_key):
Looking at the error message, it seems we want to test either:

`connect_str` is provided.

OR

All three other variable are provided.

Current test will not throw the exception if for instance only `AZURE_STORAGE_ACCOUNT_URL` is provided.

```suggestion
        if not (connect_str or (account_name and account_url and account_key)):
```

2021-05-31 07:39 UTC, yvaucher commented on attachment_azure/models/ir_attachment.py
> +        running_env = os.environ.get("RUNNING_ENV", "dev")
Might be worth documenting the `RUNNING_ENV` variable in the README. Where it comes from and what is the impact on the container name.

2021-05-31 07:39 UTC, yvaucher commented on attachment_azure/models/ir_attachment.py
> +            except exceptions.UserError:
This catch seems suspicious, `container_client` and `blob_client` are azure lib objects, I strongly doubt it raises Odoo like exceptions.

2021-05-31 07:39 UTC, yvaucher commented on attachment_azure/models/ir_attachment.py
> +                except exceptions.UserError as error:
Is this `except` at the right level? Also seems suspicious, as I doubt `upload_blob` will ever raise such an exception.

2021-05-31 07:39 UTC, yvaucher commented on attachment_azure/models/ir_attachment.py
> +            except exceptions.UserError:
same here

2021-06-01 16:16 UTC, max3903 commented
@yvaucher Thanks for the review. I believe all the comments have been taken care of.

2021-06-02 15:36 UTC, yvaucher approved these changes

2021-06-02 15:37 UTC, merged