[ADD] attachment_s3: Added the database drop flow in attachment_s3
camptocamp/odoo-cloud-platform pull request #236
Opened 2021-07-09 15:01 UTC by max3903

#223

2021-07-09 15:04 UTC, max3903 commented on attachment_s3/__init__.py
> +    env["ir.attachment"]._get_s3_bucket()
@hiren-serpentcs You also need to set the config parameter and force the storage like here:
https://github.com/ursais/odoo-template/blob/14.0/odoo/songs/setup/base.py#L51

2021-07-09 15:05 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            bucket.objects.all().delete()
@hiren-serpentcs Does this also delete the bucket itself?

2021-07-09 15:06 UTC, max3903 commented
Ping @jjscarafia

2021-07-09 18:19 UTC, jjscarafia commented
Hi @max3903 
Thanks for the ping.
IMHO, deleting the bucket when deleting the db should be optional. Not sure how, may be with an environment key? or a conf parameter? In my use case it would be very dangerous to delete the bucket.

my 2 cents

2021-07-15 13:27 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            request.env.cr.execute(sql)
@hiren-serpentcs The database is already dropped.

2021-07-15 13:28 UTC, max3903 commented on attachment_s3/controllers/main.py
> +                        REPLACE(store_fname, '/*production-master*/', '%s')
```suggestion
                        REPLACE(store_fname, '/*%s*/', '%s')
```

2021-07-15 13:29 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            """ (new_bucket_name,))
```suggestion
            """ (bucket_to_copy, new_bucket_name))
```

2021-07-15 13:30 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            _logger.exception("error reading attachment from object storage")
```suggestion
            _logger.exception("Error reading attachments from object storage.")
```

2021-07-15 14:02 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            request.env.cr.execute(sql)
@hiren-serpentcs We don't need this. The database is being dropped, why would we update it?

2021-07-15 14:04 UTC, max3903 commented on attachment_s3/__init__.py
> +    env["ir.attachment"]._get_s3_bucket()
```suggestion
    env["ir.attachment"]._get_s3_bucket()
    env["ir.config_parameter"].create({"key": "ir_attachment.location", "value": "s3"})
```

2021-07-15 14:04 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            request.env.cr.execute(sql)
```suggestion
```

2021-07-15 14:05 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            request.env.cr.execute(sql)
```suggestion
```

2021-07-15 14:53 UTC, max3903 commented on attachment_s3/controllers/main.py
> +        delete_on_drop = os.environ.get("AWS_DELETE_ON_DBDROP")
```suggestion
        delete_on_drop = os.environ.get("AWS_DELETE_ON_DBDROP", False)
```

2021-07-15 14:54 UTC, max3903 commented on attachment_s3/models/ir_attachment.py
> +        if not (access_key and secret_key and delete_on_drop):
```suggestion
        if not (access_key and secret_key):
```

2021-07-15 14:54 UTC, max3903 commented on attachment_s3/models/ir_attachment.py
> +                "* AWS_DELETE_ON_DBDROP\n"
```suggestion
```

2021-07-28 14:45 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            _logger.exception("Error reading attachments from object storage.")
```suggestion
            _logger.exception("Error writing attachments to object storage.")
```

2021-07-28 14:45 UTC, max3903 commented on attachment_s3/controllers/main.py
> +            _logger.exception("Error reading attachments from object storage.")
```suggestion
            _logger.exception("Error writing attachments to object storage.")
```

2022-06-08 13:03 UTC, nbessi requested changes
I'm not fan of this approach. That should be the role of an operator also that pose a lot of compatibility question and might be incompatible with the pod affinity/identity  philosophy promoted by Cloud providers. I would prefer to have that as a separated module to be honnest

2023-03-01 10:00 UTC, closed without merging