add conditionnal mimetype to upload file in bucket s3
camptocamp/odoo-cloud-platform pull request #404
Opened 2023-01-25 10:30 UTC by cyrilmanuel

2023-01-26 12:24 UTC, yvaucher approved these changes

2023-02-14 15:59 UTC, yvaucher commented
Seems the CI is failling but unrelated to that PR

```
ERROR: Could not find a version that satisfies the requirement pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1)) (from versions: 0.1, 0.1.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.6, 0.3, 0.4, 0.5, 0.6)
```

2023-02-14 16:52 UTC, yvaucher commented
We should change the unit tests to be run with github actions.

MQT now fails due to a change on pylint-odoo that requires a dependency which is too recent and dropped support for python <3.6.2.

https://github.com/OCA/oca-addons-repo-template/tree/master/.github/workflows

I'll make a quick patch.

2023-03-01 09:07 UTC, vrenaville approved these changes

2023-08-06 14:26 UTC, gurneyalex commented
@yvaucher did you make the quick patch?

2024-11-13 10:16 UTC, yvaucher requested changes

2024-11-13 10:16 UTC, yvaucher commented on attachment_s3/models/ir_attachment.py
> +            super(IrAttachment, attach.sudo()).write(vals)
:warning: With @sarsurgithub we discovered that this super is there to bypass the write of `ir.attachment` where it pops out the `file_size` and `checksum` fields as it is supposed to be written by this inverse function.

Thus here with this overwrite we loose this bypass.


You need to import the base ir_attachment model:

```
from odoo.addons.base.models.ir_attachment import IrAttachment as BaseIrAttachment
```
Then use the base model for the write.
```suggestion
            super(BaseIrAttachment, attach.sudo()).write(vals)
```

2024-12-15 12:02 UTC, closed without merging